config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include
from django.urls import path
from django.views import defaults as default_views
from django.views.generic import TemplateView

urlpatterns = [
    # path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
    path(
        "about/",
        TemplateView.as_view(template_name="pages/about.html"),
        name="about",
    ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("tikiti.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
    path("task/", include('tikiti.Task.urls')),
    path("", include("tikiti.Pages.urls")),
    # path('ckeditor/', include('ckeditor_uploader.urls')),
    # ...
    # Media files
    *static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT),
]


if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [
            path("__debug__/", include(debug_toolbar.urls)),
            *urlpatterns,
        ]

tikiti/Pages/urls.py
from django.urls import path
from .views import TaskSearchView,HomeTemplateVIew

app_name = 'Pages'

urlpatterns = [
    path('', HomeTemplateVIew.as_view(), name='home'),
    path('search/', TaskSearchView.as_view(), name="search"),
]

tikiti/Task/urls.py
from django.urls import path
from .views import Test, TaskListView, TaskDetailView, CreateTaskView, EditTaskMaterial,MyTaskView, DeleteTaskView,TaskAssigneeView,AddTaskMaterial, TaskIssueView,TaskPriorityView, UpdateTaskView, TaskStatusView,UpdateTaskStatusView, UpdateTaskAssigneeView,TaskSectorView

app_name = 'Task'

urlpatterns = [
    path("", TaskListView.as_view(), name='tasks'),
    path("details/<slug>/", TaskDetailView.as_view(), name="task-details"),
    path("create", CreateTaskView.as_view(), name='create'),
    path("delete/<slug>/", DeleteTaskView.as_view(), name="delete"),
    path("edit/<slug>", UpdateTaskView.as_view(), name='edit'),
    path("change-status/<slug>", UpdateTaskStatusView.as_view(), name='change-status'),
    path("change-assignee/<slug>", UpdateTaskAssigneeView.as_view(), name='change-assignee'),
    path('sector/<slug>', TaskSectorView.as_view(), name='task-sector'),
    path('status/<slug>', TaskStatusView.as_view(), name='task-status'),
    path('priority/<slug>', TaskPriorityView.as_view(), name='task-priority'),
    path('issue/<slug>', TaskIssueView.as_view(), name='task-issue'),
    path('assignee/<pk>', TaskAssigneeView.as_view(), name='task-assignee'),
    path('my-task/<username>', MyTaskView.as_view(), name='my-task'),
    path('add-materials<slug>/', AddTaskMaterial.as_view(), name='add-materials'),
    path('edit-material<slug>', EditTaskMaterial.as_view(), name='edit-materials')
    
]

tikiti/users/urls.py
from django.urls import path

from .views import user_detail_view
from .views import user_redirect_view
from .views import user_update_view

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

tikiti/Task/models.py
from django.db import models
from tikiti.users.models import User
import uuid
from django.utils.translation import gettext_lazy as _
from django.urls import reverse,reverse_lazy
from tikiti.Profile.models import Assignees
# Create your models here.

# sector


class Sector(models.Model):
    sector_name = models.CharField(max_length=60, unique=True)
    slug = models.UUIDField(unique=True, default=uuid.uuid4, editable=False)
    user = models.ForeignKey(User, related_name='user_sector', on_delete=models.CASCADE)
    description = models.TextField(max_length=255)
    is_featured = models.BooleanField(default=True)
    is_published = models.BooleanField(default=True)
    create_date = models.DateTimeField(auto_now_add=True)
    update_date = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = 'Sector'
        verbose_name_plural = 'Sector'

    def __str__(self):
        return self.sector_name


# source 

class Source(models.Model):
    source_name = models.CharField(max_length=60, unique=True)
    slug = models.UUIDField(unique=True, default=uuid.uuid4, editable=False)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    description = models.TextField(max_length=255)
    create_date = models.DateTimeField(auto_now_add=True)
    update_date = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = 'Source'
        verbose_name_plural = 'Source'

    def __str__(self):
        return self.source_name


# support types

class Support(models.Model):
    support_type = models.CharField(max_length=60, unique=True)
    slug = models.UUIDField(unique=True, default=uuid.uuid4, editable=False)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    description = models.TextField(max_length=255)
    create_date = models.DateTimeField(auto_now_add=True)
    update_date = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = 'Support'
        verbose_name_plural = 'Support'

    def __str__(self):
        return self.support_type
    
# status


class Status(models.Model):
    status = models.CharField(max_length=60, unique=True)
    slug = models.UUIDField(unique=True, default=uuid.uuid4, editable=False)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    description = models.TextField(max_length=255)
    create_date = models.DateTimeField(auto_now_add=True)
    update_date = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = 'Status'
        verbose_name_plural = 'Status'

    def __str__(self):
        return self.status
# issue


class Issue(models.Model):
    issue_type = models.CharField(max_length=60, unique=True)
    slug = models.UUIDField(unique=True, default=uuid.uuid4, editable=False)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    description = models.TextField(max_length=255)
    create_date = models.DateTimeField(auto_now_add=True)
    update_date = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = 'Issue'
        verbose_name_plural = 'Issues'

    def __str__(self):
        return self.issue_type
# priority

   
class Priority(models.Model):
    priority_type = models.CharField(max_length=60, unique=True)
    slug = models.UUIDField(unique=True, default=uuid.uuid4, editable=False)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    description = models.TextField(max_length=255)
    create_date = models.DateTimeField(auto_now_add=True)
    update_date = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = 'Priority'
        verbose_name_plural = 'Priorities'

    def __str__(self):
        return self.priority_type

#

    
# task


class Task(models.Model):
    sector = models.ForeignKey(Sector, related_name='task_sector', verbose_name =_('Sector'), on_delete= models.PROTECT) 
    ticket = models.CharField(editable=False, blank=True, max_length=100)   
    slug = models.UUIDField(unique=True, default=uuid.uuid4, editable=False)
    source = models.ForeignKey(Source, related_name="task_source", verbose_name=_('Lead'),  on_delete=models.PROTECT)
    issue_type = models.ForeignKey(Issue, related_name="task_issue", verbose_name=_("Issue Type"), on_delete=models.PROTECT)
    customer_id = models.CharField(_('Customer No'), max_length=40, null=True, blank=True)
    title = models.CharField(_('Title'), max_length=1000)
    description = models.TextField(_('Description'))
    support_type = models.ForeignKey(Support, related_name="task_support_type", verbose_name=_('Support Type'), on_delete=models.PROTECT, blank=True, null=True)
    status = models.ForeignKey(Status, related_name="task_status", verbose_name=_('Status'), on_delete=models.PROTECT,default=2)
    priority = models.ForeignKey(Priority, related_name="task_priority", verbose_name=_('Priority'), on_delete=models.PROTECT)
    start_date = models.DateTimeField(_("Start Date"), blank=True, null=True)
    end_date = models.DateTimeField(_("End Date"), blank=True, null=True)
    assigned_to = models.ForeignKey(Assignees, related_name='task_assignee', verbose_name=_('Assignee'), on_delete=models.CASCADE,default=1)
    created_by = models.ForeignKey(User, on_delete=models.PROTECT, verbose_name='Created By')
    updated_by = models.ForeignKey(User, on_delete=models.PROTECT, related_name='user_update_task', verbose_name='Update User', blank=True, null=True)
    create_date = models.DateTimeField(auto_now_add=True)
    update_date = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = 'Task'
        verbose_name_plural = 'Tasks'

    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse_lazy('Task:task-details', kwargs={'slug': self.slug})

    

# task files

class TaskFiles(models.Model):
    task = models.ForeignKey(Task, related_name="task_files", on_delete=models.CASCADE)
    file = models.FileField(_('Attachments'), upload_to='tasks/attachement')    
    create_date = models.DateTimeField(auto_now_add=True)
    update_date = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = 'Task File'
        verbose_name_plural = 'Task Files'

    def __str__(self):
        return f"{self.task.title}-{self.id}"
    
# task history


class TaskHistory(models.Model):
    task = models.ForeignKey(Task, on_delete=models.CASCADE)
    slug = models.UUIDField(unique=True, default=uuid.uuid4, editable=False)
    previous_status = models.CharField(max_length=30)
    current_status = models.CharField(max_length=30)
    previous_assignee = models.CharField(max_length=30)
    current_assignee = models.CharField(max_length=30)    
    create_date = models.DateTimeField(auto_now_add=True)
    update_date = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = 'Task History'
        verbose_name_plural = 'Task History'

    def __str__(self):
        return f"{self.task.title}-{self.id}"
# task comments

# Task Comments


class TaskComment(models.Model):
    task = models.ForeignKey(Task, verbose_name=_("Task"),related_name='comments', on_delete=models.CASCADE)
    user = models.ForeignKey(User, verbose_name=_("User"), on_delete=models.CASCADE)
    comment = models.TextField(max_length=1000)
    create_date = models.DateTimeField(auto_now_add=True)
    update_date = models.DateField(auto_now=True)

    class Meta:
        verbose_name ='Task Comment'

        def __str__(self):
            return f"{self.task.title}"
        
class TaskMaterial(models.Model):
    task = models.ForeignKey(Task, related_name='task_material', on_delete= models.PROTECT)
    user = models.ForeignKey(Assignees, related_name='assignee_material',on_delete=models.PROTECT)
    slug = models.UUIDField(unique=True, default=uuid.uuid4, editable=False)
    router = models.CharField(_("Router"), max_length=30, blank=True, null= True)
    rj45 = models.IntegerField(_("RJ45 Connectors"),blank=True, null=True )
    outdoor_cable = models.IntegerField(_("Outdoor Drop Cable"),blank=True, null=True )
    indoor_cable = models.IntegerField(_("Indoor Drop Cable"),blank=True, null=True )
    cat6_indoor_cable = models.IntegerField(_("CAT6 Indoor Cable"),blank=True, null=True )
    patchcode_apc = models.IntegerField(_("Patch Code LC/APC/-SC/APC"),blank=True, null=True )
    patchcode_upc = models.IntegerField(_("Patch Code LC/APC/-SC/UPC"),blank=True, null=True )
    loaded_atb = models.IntegerField(_("Loaded ATB"),blank=True, null=True )
    empty_atb = models.IntegerField(_("Empty ATB"),blank=True, null=True )
    splitter_8 = models.IntegerField(_("Splitter 1 by 8"),blank=True, null=True )
    splitter_4 = models.IntegerField(_("Splitter 1 by 4"),blank=True, null=True )
    splitter_2 = models.IntegerField(_("Splitter 1 by 2"),blank=True, null=True )
    splitter_16 = models.IntegerField(_("Splitter 1 by 16"),blank=True, null=True )
    fat_4 = models.IntegerField(_("FAT 1 by 4"),blank=True, null=True )   
    fat_8 = models.IntegerField(_("FAT 1 by 8"),blank=True, null=True )    
    router_charger = models.IntegerField(_("Router Charger"),blank=True, null=True )
    poe = models.IntegerField(_("POE Adapter"),blank=True, null=True )
    sleeves = models.IntegerField(_("Sleeves"),blank=True, null=True )    
    create_date = models.DateTimeField(auto_now_add=True)
    update_date = models.DateField(auto_now=True)

tikiti/Pages/views.py
from django.shortcuts import render
from tikiti.Task.models import Task, Status, Priority
from django.views.generic import ListView, TemplateView
from .forms import TaskSearchForm
from django.shortcuts import get_object_or_404
from django.db.models import Q
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
# Create your views here.


class HomeTemplateVIew(LoginRequiredMixin, TemplateView):
    template_name = 'pages/home.html'
    model = Task

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["statuses"] = Status.objects.all()
        context['priorities'] = Priority.objects.all()
        return context



class TaskSearchView(LoginRequiredMixin, ListView):
    model = Task
    template_name = 'pages/search.html'
    context_object_name = 'results'
    # form_class = TaskSearchForm

    def get_queryset(self):
        queryset = super().get_queryset().select_related('sector', 'source', 
                                                         'issue_type','assigned_to')
        self.form = TaskSearchForm(self.request.GET or None)
    
        if self.form.is_valid():
            title = self.form.cleaned_data.get('title')
            # priority = self.form.cleaned_data.get("priority")
            priority = self.request.GET.get('priority', None)
            # status = self.form.cleaned_data.get("status")
            status = self.request.GET.get("status", None)

            if title:
                queryset = queryset.filter(title__icontains=title)

            if priority not in [None, "", "0", '999']:  # and priority != '0' and priority != '999999':
                try:                    
                    priority = Priority.objects.get(pk=int(priority))
                    queryset = queryset.filter(Q(priority__priority_type__icontains= priority.priority_type))
                except (ValueError, Priority.DoesNotExists):
                    pass

            if status not in [None, "", "0", '999']:
                try:
                    status = Status.objects.get(pk=int(status))
                    queryset = queryset.filter(Q(status__status__icontains= status.status))
                except (ValueError, Status.DoesNotExists):
                    pass
        
        return queryset
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        status_id = self.request.GET.get('status', None)
        # if status_id == '0':
        #     context['status'] = 'All Statuses'
        # else:
        #     status = get_object_or_404(Status, pk=status_id)
        #     context['status'] = status.status

        context["search_form"] = self.form
        context['statuses'] = Status.objects.all()
        context['priorities'] = Priority.objects.all()
        return context
    
    

tikiti/Profile/views.py
from django.shortcuts import render

# Create your views here.

tikiti/users/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.db.models import QuerySet
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.views.generic import DetailView
from django.views.generic import RedirectView
from django.views.generic import UpdateView

from tikiti.users.models import User


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


user_detail_view = UserDetailView.as_view()


class UserUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = User
    fields = ["name"]
    success_message = _("Information successfully updated")

    def get_success_url(self) -> str:
        assert self.request.user.is_authenticated  # type guard
        return self.request.user.get_absolute_url()

    def get_object(self, queryset: QuerySet | None=None) -> User:
        assert self.request.user.is_authenticated  # type guard
        return self.request.user


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self) -> str:
        return reverse("users:detail", kwargs={"username": self.request.user.username})


user_redirect_view = UserRedirectView.as_view()

tikiti/templates/task/add-materials.html
{% extends 'base.html'%}
{%block title %}Add Materials{%endblock%}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
<div class="page-content">

    <!-- Start home -->
    <section class="page-title-box">
        
        <!--end container-->
    </section> 
    <!-- end home -->

    


    <!-- START CONTACT-PAGE -->
    <section class="section bg-warnjing" style="background-color:rgba( 244, 246, 247 )">
        <div class="container">
            <div class="row align-items-center mt-5">
                <div class="col-lg-12 mx-auto border border-white mt-2 shadow-lg p-3 mb-5 bg-body rounded">
                    <div class="">
                    <div class="section-title mt-4  mt-lg-0 ">
                        <h3 class="title text-center">Add Materials Form</h3>
                                               
                        <form method="post" enctype="multipart/form-data" class="contact-form mt-4" name="myForm" id="myForm">
                            {% csrf_token %}
                            {{ form|crispy}}
                            <div class="d-grid gap-2 col-6 mx-auto">
                              <button type="submit" id="submit" name="submit" class="btn btn-primary"> Add Materials<i class="uil uil-message ms-1"></i></button>
                            </div>
                        </form>
                        <!--end form-->
                    </div>
                </div>
                
                </div><!--end col-->
                
            </div>
            <!--end row-->
        </div>
        <!--end container-->
    </section>
    <!-- START CONTACT-PAGE -->

   

</div>
<!-- End Page-content -->


{% endblock %}


<label


</label> <input type="number" name="fat_8" class="numberinput form-control" id="id_fat_8"> </div> <div id="div_id_router_charger" class="mb-3"> <label
    for="id_router_charger" class="form-label">
    Router Charger
</label> <input type="number" name="router_charger" class="numberinput form-control" id="id_router_charger"> </div> <div id="div_id_poe" class="mb-3"> <label
    for="id_poe" class="form-label">
    POE Adapter
</label> <input type="number" name="poe" class="numberinput form-control" id="id_poe"> </div> <div id="div_id_sleeves" class="mb-3"> <label
    for="id_sleeves" class="form-label">
    Sleeves
</label> <input type="number" name="sleeves" class="numberinput form-control" id="id_sleeves"> </div>

tikiti/templates/task/create-task.html
{% extends 'base.html'%}
{%block title %}Create Task {%endblock%}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
<div class="page-content">

    <!-- Start home -->
    <section class="page-title-box">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-md-6">
                    <div class="text-center text-white">
                        <h3 class="mb-4">Contact</h3>
                        <div class="page-next">
                            <nav class="d-inline-block" aria-label="breadcrumb text-center">
                                <ol class="breadcrumb justify-content-center">
                                    <li class="breadcrumb-item"><a href="index.html">Home</a></li>
                                    <li class="breadcrumb-item"><a href="javascript:void(0)">Contact</a></li>
                                    <li class="breadcrumb-item active" aria-current="page"> Contact </li>
                                </ol>
                            </nav>
                        </div>
                    </div>
                </div>
                <!--end col-->
            </div>
            <!--end row-->
        </div>
        <!--end container-->
    </section> 
    <!-- end home -->

    <!-- START SHAPE -->
    <div class="position-relative" style="z-index: 1">
        <div class="shape">
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1440 250">
                <path fill="#FFFFFF" fill-opacity="1"
                    d="M0,192L120,202.7C240,213,480,235,720,234.7C960,235,1200,213,1320,202.7L1440,192L1440,320L1320,320C1200,320,960,320,720,320C480,320,240,320,120,320L0,320Z"></path>
            </svg>
        </div>
    </div>
    <!-- END SHAPE -->


    <!-- START CONTACT-PAGE -->
    <section class="section bg-warnjing" style="background-color:rgba( 244, 246, 247 )">
        <div class="container">
            <div class="row align-items-center mt-5">
                <div class="col-lg-12 mx-auto border border-white mt-2 shadow-lg p-3 mb-5 bg-body rounded">
                    <div class="">
                    <div class="section-title mt-4  mt-lg-0 ">
                        <h3 class="title text-center">Create Task Form</h3>
                                               
                        <form method="post" enctype="multipart/form-data" class="contact-form mt-4" name="myForm" id="myForm">
                            {% csrf_token %}
                            {{ form|crispy}}
                            <div class="d-grid gap-2 col-6 mx-auto">
                              <button type="submit" id="submit" name="submit" class="btn btn-primary"> Create Task<i class="uil uil-message ms-1"></i></button>
                            </div>
                        </form>
                        <!--end form-->
                    </div>
                </div>
                </div><!--end col-->
                
            </div>
            <!--end row-->
        </div>
        <!--end container-->
    </section>
    <!-- START CONTACT-PAGE -->

   

</div>
<!-- End Page-content -->


{% endblock %}

tikiti/templates/task/delete-task.html
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Delete">
</form>

tikiti/templates/task/task-issue.html
{% extends 'base.html'%}
{% block title%}Task {% endblock%}
{%load static%}
{% load default_tags %}
{%block content %}
<div class="page-content">

    <!-- Start home -->
    <section class="page-title-box">
        
    </section>
    <!-- end home -->

    


    <!-- START JOB-LIST -->
    <section class="section min-vh-100">
        <div class="container">
            <div class="row">

                <div class="col-lg-10">
                    <div class="me-lg-5">  
                        <div class="wedget-popular-title mt-4 ">
                            <h6><span class="fs-16 text-muted"> {{issue.issue_type}} Tasks </span></h6>
                           
                        </div><!--end wedget-popular-title-->                      
                        
                        <div>                                         
                            {% for task in tasks %}
                            <div class="job-box card mt-4">
                                <div class="p-4">
                                    <div class="row">                                        
                                        <div class="col-lg-11">
                                            <div class="mt-3 mt-lg-0">
                                                <h5 class="fs-17 mb-1"><a href="{{task.get_absolute_url}}" class="text-dark">{{task.ticket}} / {{task.title}}</a> </h5>
                                                <ul class="list-inline mb-0">
                                                    <li class="list-inline-item">
                                                        <p class="text-muted fs-14 mb-0">Created: {{task.create_date}}</p>
                                                    </li>
                                                    <li class="list-inline-item">
                                                        <p class="text-muted fs-14 mb-0">{{task.assigned_to}}</p>
                                                    </li>
                                                    <li class="list-inline-item">
                                                        <p class="text-muted fs-14 mb-0"><i class="mdi mdi-map-marker"></i> {{task.sector}}</p>
                                                    </li>
                                                    <li class="list-inline-item">
                                                        <p class="text-muted fs-14 mb-0"><i class="uil uil-wallet"></i> {{task.issue_type}}</p>
                                                    </li>
                                                    <li class="list-inline-item">
                                                        <p class="text-muted fs-14 mb-0"><i class="uil uil-wallet"></i> {% include 'includes/status.html' %}</p>
                                                    </li>
                                                </ul>
                                                
                                            </div>
                                        </div><!--end col-->
                                    </div><!--end row-->
                                   
                                </div>
                               
                            </div>
                            <!--end job-box-->  
                            {% empty %}
                            <div class="job-box card mt-4 shadow-lg p-3 mb-5 bg-body rounded">
                                <div class="p-4">
                                    <div class="row">                                        
                                        <div class="col-lg-11">
                                            <div class="mt-3 mt-lg-0 text-center ">                                      
                                                <p class="text-muted fs-3 mb-0">No Task Found !</p>                                                
                                            </div>
                                            
                                        </div><!--end col-->
                                    </div><!--end row-->
                                   
                                </div>
                               
                            </div>
                            {% endfor%}
    
    
                        </div>
                        <!-- End Job-list -->
                        {% if page_obj.number > 1 %}
                        <div class="row">
                            <div class="col-lg-12 mt-4 pt-2">
                                <nav aria-label="Page navigation example">
                                    <ul class="pagination job-pagination mb-0 justify-content-center">
                                        {% if page_obj.has_previous %}
                                            <li class="page-item ">
                                                <a class="page-link" href="?page={{page_obj.previous_page_number}}" tabindex="-1">
                                                    <i class="mdi mdi-chevron-double-left fs-15"></i>
                                                </a>
                                            </li>
                                            {% if page_obj.number > 3 %}
                                                <a class="page-link" href="?page=1">1</a>
                                                {% if page_obj.number > 4 %}
                                                    <span>...</span>
                                                {% endif %}
                                            {% endif %}
                                        {% endif %}
                                        {% for num in page_obj.paginator.page_range %}
                                            {% if page_obj.number == num %}
                                                    <li class="page-item active"><a class="page-link" href="?page={{num}}">{{num}}</a></li>
                                            {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3'%}
                                                 <li class="page-item"><a class="page-link" href="?page={{num}}">{{num}}</a></li>
                                                {% endif%}
                                                {% endfor%}

                                        {% if page_obj.has_next %}
                                        {% if page_obj.number < page_obj.paginator.num_pages|add:'-3' %}
                                            <span>...</span>
                                            <li class="page-item"><a class="page-link" href="?page={{page_obj.paginator.num_pages}}">{{page_obj.paginator.num_pages}}</a></li>                                            
                                            {% elif page_obj.number < page_obj.paginator.num_pages|add:'-2'%}
                                            <li class="page-item"><a class="page-link" href="?page={{page_obj.paginator.num_pages}}">{{page_obj.paginator.num_pages}}</a></li>
                                            {% endif %}
                                       <li class="page-item">
                                            <a class="page-link" href="?pages={{page_obj.next_page_number}}">
                                                <i class="mdi mdi-chevron-double-right fs-15"></i>
                                            </a>
                                        </li>
                                        {% endif %}
                                    </ul>
                                </nav>
                            </div><!--end col-->
                        </div><!-- end row -->
                        {% endif %}
                    </div>

                </div>
                
            </div>
        </div>
    </section>
    <!-- END JOB-LIST -->

    

</div>
<!-- End Page-content -->
{% endblock%}

tikiti/templates/task/test.html
test