config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include
from django.urls import path
from django.views import defaults as default_views
from django.views.generic import TemplateView

urlpatterns = [
    # path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
    path(
        "about/",
        TemplateView.as_view(template_name="pages/about.html"),
        name="about",
    ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("tikiti.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
    path("task/", include('tikiti.Task.urls')),
    path("", include("tikiti.Pages.urls")),
    # path('ckeditor/', include('ckeditor_uploader.urls')),
    # ...
    # Media files
    *static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT),
]


if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [
            path("__debug__/", include(debug_toolbar.urls)),
            *urlpatterns,
        ]

tikiti/Pages/urls.py
from django.urls import path
from .views import TaskSearchView,HomeTemplateVIew

app_name = 'Pages'

urlpatterns = [
    path('', HomeTemplateVIew.as_view(), name='home'),
    path('search/', TaskSearchView.as_view(), name="search"),
]

tikiti/Task/urls.py
from django.urls import path
from .views import Test, TaskListView, TaskDetailView, CreateTaskView, EditTaskMaterial,MyTaskView, DeleteTaskView,TaskAssigneeView,AddTaskMaterial, TaskIssueView,TaskPriorityView, UpdateTaskView, TaskStatusView,UpdateTaskStatusView, UpdateTaskAssigneeView,TaskSectorView

app_name = 'Task'

urlpatterns = [
    path("", TaskListView.as_view(), name='tasks'),
    path("details/<slug>/", TaskDetailView.as_view(), name="task-details"),
    path("create", CreateTaskView.as_view(), name='create'),
    path("delete/<slug>/", DeleteTaskView.as_view(), name="delete"),
    path("edit/<slug>", UpdateTaskView.as_view(), name='edit'),
    path("change-status/<slug>", UpdateTaskStatusView.as_view(), name='change-status'),
    path("change-assignee/<slug>", UpdateTaskAssigneeView.as_view(), name='change-assignee'),
    path('sector/<slug>', TaskSectorView.as_view(), name='task-sector'),
    path('status/<slug>', TaskStatusView.as_view(), name='task-status'),
    path('priority/<slug>', TaskPriorityView.as_view(), name='task-priority'),
    path('issue/<slug>', TaskIssueView.as_view(), name='task-issue'),
    path('assignee/<pk>', TaskAssigneeView.as_view(), name='task-assignee'),
    path('my-task/<username>', MyTaskView.as_view(), name='my-task'),
    path('add-materials<slug>/', AddTaskMaterial.as_view(), name='add-materials'),
    path('edit-material<slug>', EditTaskMaterial.as_view(), name='edit-materials')
    
]

tikiti/users/urls.py
from django.urls import path

from .views import user_detail_view
from .views import user_redirect_view
from .views import user_update_view

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

tikiti/Pages/models.py
from django.db import models

# Create your models here.

tikiti/Pages/forms.py
from django import forms
from tikiti.Task.models import Task, Status, Priority
from django.utils.translation import gettext as _


class TaskSearchForm(forms.Form):
    title = forms.CharField(required=False, label="Title", widget=forms.TextInput(attrs={"class":"form-control title-search"})),
    priority = forms.ModelChoiceField(required=False, label="Priority", queryset=Priority.objects.all(), empty_label=_("None"),
                                      widget=forms.Select(attrs={"class":"form-control"}))
    status = forms.ModelChoiceField(required=False, label="Status", queryset=Status.objects.all(), empty_label="None",
                                    widget=forms.Select(attrs={"class":"form-control"}))

tikiti/Pages/views.py
from django.shortcuts import render
from tikiti.Task.models import Task, Status, Priority
from django.views.generic import ListView, TemplateView
from .forms import TaskSearchForm
from django.shortcuts import get_object_or_404
from django.db.models import Q
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
# Create your views here.


class HomeTemplateVIew(LoginRequiredMixin, TemplateView):
    template_name = 'pages/home.html'
    model = Task

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["statuses"] = Status.objects.all()
        context['priorities'] = Priority.objects.all()
        return context



class TaskSearchView(LoginRequiredMixin, ListView):
    model = Task
    template_name = 'pages/search.html'
    context_object_name = 'results'
    # form_class = TaskSearchForm

    def get_queryset(self):
        queryset = super().get_queryset().select_related('sector', 'source', 
                                                         'issue_type','assigned_to')
        self.form = TaskSearchForm(self.request.GET or None)
    
        if self.form.is_valid():
            title = self.form.cleaned_data.get('title')
            # priority = self.form.cleaned_data.get("priority")
            priority = self.request.GET.get('priority', None)
            # status = self.form.cleaned_data.get("status")
            status = self.request.GET.get("status", None)

            if title:
                queryset = queryset.filter(title__icontains=title)

            if priority not in [None, "", "0", '999']:  # and priority != '0' and priority != '999999':
                try:                    
                    priority = Priority.objects.get(pk=int(priority))
                    queryset = queryset.filter(Q(priority__priority_type__icontains= priority.priority_type))
                except (ValueError, Priority.DoesNotExists):
                    pass

            if status not in [None, "", "0", '999']:
                try:
                    status = Status.objects.get(pk=int(status))
                    queryset = queryset.filter(Q(status__status__icontains= status.status))
                except (ValueError, Status.DoesNotExists):
                    pass
        
        return queryset
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        status_id = self.request.GET.get('status', None)
        # if status_id == '0':
        #     context['status'] = 'All Statuses'
        # else:
        #     status = get_object_or_404(Status, pk=status_id)
        #     context['status'] = status.status

        context["search_form"] = self.form
        context['statuses'] = Status.objects.all()
        context['priorities'] = Priority.objects.all()
        return context
    
    

tikiti/Profile/views.py
from django.shortcuts import render

# Create your views here.

tikiti/Task/views.py
from django.shortcuts import render,get_object_or_404,redirect
from tikiti.Task.models import Task, Sector, Source, Support, Status, Issue, Priority, TaskHistory, TaskFiles,TaskMaterial,TaskComment#,Assignee
from tikiti.Profile.models import Assignees
from django.views.generic import ListView,DetailView,CreateView,DeleteView,UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from .forms import TaskForm, UpdateTaskForm, UpdateTaskStatusForm, UpdateTaskAssigneeForm,COmmentTaskForm,TaskMaterialForm,TaskMaterialEditForm
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy
from django.contrib import messages
from django.db.models import Count
from django.utils.text import slugify
from django.http import Http404
from tikiti.users.models import User
# Create your views here.


class TaskListView(LoginRequiredMixin, ListView):
    model = Task
    template_name = "task/tasks.html"
    login_url = ""
    context_object_name = 'tasks'
    paginate_by = 20 

    def get_queryset(self):
        queryset = Task.objects.select_related().defer().order_by("-create_date")
        return queryset
    # more info
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["task_sectors"] = Sector.objects.annotate(sector_count=Count('task_sector')).prefetch_related("task_sector")
        context['task_prioritys'] = Priority.objects.annotate(priority_count=Count("task_priority")).prefetch_related("task_priority")
        context['task_statuses'] = Status.objects.annotate(status_count=Count("task_status")).prefetch_related("task_status")
        context['task_issues'] = Issue.objects.annotate(issue_count=Count("task_issue")).prefetch_related("task_issue")
        context['task_assigness'] = Assignees.objects.annotate(assignee_count=Count("task_assignee")).prefetch_related("task_assignee")
        context['statuses'] = Status.objects.all()
        context['priorities'] = Priority.objects.all()
        return context
    

class TaskDetailView(LoginRequiredMixin, DetailView):
    model = Task
    template_name = 'task/task-details.html'
    context_object_name = "task"    
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        #task = self.get_object()
        context['status_form'] = UpdateTaskStatusForm(instance=self.object)
        context['assignee_form'] = UpdateTaskAssigneeForm(instance=self.object)
        context['comments'] = self.object.comments.all().order_by('-create_date')
        context['comment_form'] = COmmentTaskForm()
        context['materials'] = TaskMaterial.objects.filter(task=self.object)
        return context
    
    def post(self,request,*args, **kwargs):
        task = self.get_object()
        form = COmmentTaskForm(request.POST)
        
        if form.is_valid():
            comment=form.save(commit=False)
            comment.task=task
            comment.user=request.user
            comment.save()
            return redirect(task.get_absolute_url())
        context = self.get_context_data()
        context['comment_form'] = form
        return self.render_to_response(context)
        


class CreateTaskView(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    model = Task
    form_class = TaskForm
    template_name = 'task/create-task.html'
    success_message = "Task Created Successfully"
    # success_url = "/"
    
    def form_valid(self, form):
        task = form.save(commit=False)
        task.created_by = self.request.user        
        task.save()
        files = self.request.FILES.getlist('files')
        for file in files:
            TaskFiles.objects.create(task=task, file=file)        
        return super(CreateTaskView, self).form_valid(form)


class UpdateTaskView(LoginRequiredMixin, UpdateView):
    model = Task
    form_class = UpdateTaskForm
    template_name = 'task/update-task.html'
    success_message = "Task Edited Successfully"
    # success_url = "/"
    
    def form_valid(self, form):
        task = form.save(commit=False)
        task.save()
        files = self.request.FILES.getlist('files')
        for file in files:
            TaskFiles.objects.create(task=task, file=file)   
        # messages.success(self.request("Task Update Successfully"))     
        return super(UpdateTaskView, self).form_valid(form)
    
    # def form_invalid(self, form):
    #     messages.error(self.request("Task Update Unsuccessfull"))
    #     return super(UpdateTaskView, self).form_invalid(form)
        
    
    

class UpdateTaskStatusView(LoginRequiredMixin, UpdateView):
    model = Task
    form_class = UpdateTaskStatusForm
    template_name = 'task/update-status.html'
    success_message = "Task Status Changed"
    #success_url = "/"
    

# class TaskCommentsView(LoginRequiredMixin, CreateView):
#     model = TaskComment
#     success_message ="Comment Added"
#     form_class = COmmentTaskForm

class UpdateTaskAssigneeView(LoginRequiredMixin, UpdateView):
    model = Task
    form_class = UpdateTaskAssigneeForm
    template_name = 'task/update-assignee.html'
    success_message = "Task Assignee Changed"
    # success_url = "/"
    
   

class DeleteTaskView(LoginRequiredMixin, DeleteView):
    model = Task
    template_name = 'task/delete-task.html'
    success_message = 'Task Deleted'
    success_url = '/'
    

class TaskSectorView(LoginRequiredMixin, ListView):
    model = Task
    context_object_name = 'tasks'
    paginate_by = 20
    template_name = 'task/task-sector.html'

    def get_queryset(self):
        self.sector = get_object_or_404(Sector, slug=self.kwargs.get('slug'))
        return super().get_queryset().filter(sector=self.sector).select_related('sector', 'source', 
                                                        'issue_type', 'assigned_to').order_by("-create_date")    

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["sector"] = self.sector 
        return context

    
class TaskStatusView(LoginRequiredMixin, ListView):
    model = Task
    context_object_name = 'tasks'
    template_name = 'task/task-status.html'
    paginate_by = 20

    def get_queryset(self):
        self.status = get_object_or_404(Status, slug=self.kwargs.get('slug'))
        return super().get_queryset().filter(status=self.status).select_related('sector', 'source', 
                                                        'issue_type', 'assigned_to').order_by("-create_date")  
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['status'] = self.status
        return context
    
    

class TaskPriorityView(LoginRequiredMixin, ListView):
    model = Task
    context_object_name = 'tasks'
    template_name = 'task/task-priority.html'
    paginate_by = 20

    def get_queryset(self):
        self.priority = get_object_or_404(Priority, slug=self.kwargs.get('slug'))
        return super().get_queryset().filter(priority=self.priority).select_related('sector', 'source', 
                                                        'issue_type', 'assigned_to').order_by("-create_date")  
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["priority"] = self.priority
        return context
    
    

class TaskIssueView(LoginRequiredMixin, ListView):
    model = Task
    context_object_name = 'tasks'
    template_name = 'task/task-issue.html'
    paginate_by = 20

    def get_queryset(self):
        self.issue_type = get_object_or_404(Issue, slug=self.kwargs.get('slug'))
        return super().get_queryset().filter(issue_type=self.issue_type).select_related('sector', 'source', 
                                                        'issue_type', 'assigned_to').order_by("-create_date") 
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["issue_type"] = self.issue_type
        return context
    


class TaskAssigneeView(LoginRequiredMixin, ListView):
    model = Task
    context_object_name = 'tasks'
    template_name = 'task/task-assignee.html'
    paginate_by = 20

    def get_queryset(self):
        self.assignee_to = get_object_or_404(Assignees, id=self.kwargs.get('pk'))
        return super().get_queryset().filter(assigned_to=self.assignee_to).select_related('sector', 'source', 
                                                        'issue_type', 'assigned_to').order_by("-create_date")  
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["assigned_to"] = self.assignee_to
        context['task_status_count'] = Task.objects.filter(assigned_to=self.assignee_to).select_related('task_assignee', 'task_status').values("assigned_to__assignee").annotate(count=Count('id'))
        return context
    
    

class MyTaskView(LoginRequiredMixin, ListView):
    model = Task
    template_name = 'task/my-tasks.html'
    paginate_by = 20
    context_object_name = 'tasks'

    def get_assigned_user(self):
        username = slugify(self.kwargs.get("username", '').strip())
        try:
            user = User.objects.get(username=username)
            assigned_user = Assignees.objects.select_related("assignee").get(assignee=user)
            return assigned_user
        
        except User.DoesNotExist:
            raise Http404("User not found")

    def get_queryset(self):
        self.assigned_user = self.get_assigned_user()
        queryset = Task.objects.filter(assigned_to=self.assigned_user).select_related('assigned_to').order_by("-create_date")
        return queryset
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["assigned_user"] = self.assigned_user

tikiti/templates/includes/footer.html
                <!-- START FOOTER -->
              
                <!-- END FOOTER -->

                <!-- START FOOTER-ALT -->
                <div class="footer-alt">
                    <div class="container">
                        <div class="row">
                            <div class="col-lg-12">
                                <p class="text-white-50 text-center mb-0">
                                    <script>document.write(new Date().getFullYear())</script> &copy; IKomol Task Management
                                </p>
                            </div><!--end col-->
                        </div><!--end row-->
                    </div><!--end container-->
                </div>
                <!-- END FOOTER -->
                
               

tikiti/templates/includes/header.html
{%load static %}

            <nav class="navbar navbar-expand-lg fixed-top sticky" id="navbar">
                <div class="container-fluid custom-container">
                    <a class="navbar-brand text-dark fw-bold me-auto" href="{% url 'Pages:home' %}">
                        <img src="{% static 'images/logo/logo.png'%}" height="22" alt="I_Task" class="logo-dark" />
                        <img src="{% static 'images/logo/logo.png'%}" height="22" alt="I_Task" class="logo-light" />
                    </a>
                    <div>
                        <button class="navbar-toggler me-3" type="button" data-bs-toggle="collapse"
                            data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-label="Toggle navigation">
                            <i class="mdi mdi-menu"></i>
                        </button>
                    </div>
                    <div class="collapse navbar-collapse" id="navbarCollapse">
                        <ul class="navbar-nav mx-auto navbar-center">
                            <li class="nav-item">
                                <a href="{% url 'Pages:home' %}" class="nav-link">Home</a>
                            </li>
                            <li class="nav-item">
                                <a href="{% url 'Task:tasks' %}" class="nav-link">Tasks</a>
                            </li>
                            <li class="nav-item">
                                <a href="{% url 'Task:create' %}" class="nav-link">Create</a>
                            </li>                            
                            
                        </ul><!--end navbar-nav-->
                    </div>
                    <!--end navabar-collapse-->
                    <ul class="header-menu list-inline d-flex align-items-center mb-0">
                       
                        <li class="list-inline-item dropdown">
                            <a href="javascript:void(0)" class="header-item" id="userdropdown" data-bs-toggle="dropdown"

                                aria-expanded="false">
                                {% if request.user.is_authenticated %}
                                <span class="d-none d-md-inline-block fw-medium">{{user.username}}</span>
                                {% else %}
                                <span class="d-none d-md-inline-block fw-medium">Guest</span>
                                {% endif %}
                            </a>
                            <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="userdropdown">
                                 
                                {% if request.user.is_authenticated %} 
                                <li><a class="dropdown-item" href="{% url 'Task:my-task' request.user.username %}">My Tasks</a></li>                              
                                <li><a class="dropdown-item" href="{% url 'users:detail' request.user.username %}">My Profile</a></li>
                                <li><a class="dropdown-item" href="{% url 'account_logout' %}">Logout</a></li>
                                {% else %}
                                {% if ACCOUNT_ALLOW_REGISTRATION%}                                                              
                                <li><a class="dropdown-item" href="{% url 'account_signup' %}">Sign Up</a></li>
                                {% endif%}
                                <li><a class="dropdown-item" href="{% url 'account_login' %}">Sign In</a></li> 
                                {% endif %}
                                
                            </ul>
                        </li>
                    </ul><!--end header-menu-->
                </div>
                <!--end container-->
            </nav>
            <!-- Navbar End -->


            
            <!-- END SIGN-UP MODAL -->

tikiti/templates/includes/search_form.html
    <form  method="get" action="{% url 'Pages:search' %}">
        <div class="row g-2">
            <div class="col-lg-3 col-md-6">
                <div class="filler-job-form">
                    <i class="uil uil-briefcase-alt"></i>
                    <input type="search" class="form-control filter-job-input-box" id="exampleFormControlInput1" placeholder="Title" name="title">
                </div>
            </div><!--end col-->
            <div class="col-lg-3 col-md-6">
                <div class="filler-job-form">
                    <i class="uil uil-location-point"></i>
                    <select class="form-select" data-trigger name="priority" id="choices-single-location" aria-label="Default select example">
                        <option value="0">All Priority</option> 
                        {% comment %} <option value="">None</option>  {% endcomment %}
                        {% for priority in priorities%}
                        <option value="{{priority.pk}}">{{priority.priority_type}}</option>  
                        {% endfor %}                                              
                        
                    </select>
                </div>
            </div><!--end col-->
            
            <div class="col-lg-3 col-md-6">
                <div class="filler-job-form">
                    <i class="uil uil-clipboard-notes"></i>
                    
                    <select class="form-select " data-trigger name="status" id="choices-single-categories" aria-label="Default select example">
                        <option value="0">All Status</option> 
                        {% comment %} <option value="">None</option>  {% endcomment %}
                        {% for status in statuses %}                                                
                        <option value="{{status.pk}}">{{status.status}}</option>
                        {% endfor %}
                    </select>
                </div>
            </div><!--end col-->
            <div class="col-lg-3 col-md-6">
                <button type="submit" id="submit" name="submit" class="btn btn-primary w-100"><i class="uil uil-filter"></i> Fliter</button>
            </div><!--end col-->
        </div><!--end row-->
    </form>

tikiti/templates/includes/status.html
{% if task.status.status == 'New' %}
                                                            
<span class="badge bg-secondary mt-1">{{task.status}}</span>

{% elif task.status.status  == "Analysis"  %}
<span class="badge bg-primary mt-1">{{task.status}}</span>

{% elif task.status.status  == "Working On It"  %}
<span class="badge bg-info mt-1">{{task.status}}</span>

{% elif task.status.status  == "Deliver"  %}
<span class="badge bg-success mt-1">{{task.status}}</span>

{% elif task.status.status == "Closed"  %}
<span class="badge bg-success mt-1">{{task.status}}</span>

{% elif task.status.status  == "Reopened"  %}
<span class="badge bg-dark mt-1">{{task.status}}</span>
{% endif %}